const data = [
  {
    location_id: "734531",
    name: "Narayani Heights",
    latitude: "23.111837",
    longitude: "72.62926",
    num_reviews: "220",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/06/bb/2b/36/narayani-heights.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/06/bb/2b/36/narayani-heights.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/06/bb/2b/36/narayani-heights.jpg",
          height: "1334",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/06/bb/2b/36/narayani-heights.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/06/bb/2b/36/narayani-heights.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2014-10-14T10:53:23-0400",
      caption: "Execuitve Suite Room",
      id: "112929590",
      helpful_votes: "7",
      published_date: "2014-10-14T10:53:23-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2021",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2021_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2021",
      },
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2018",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2018_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2018",
      },
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2017",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2017_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2017",
      },
    ],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.604705572128296",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "1",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#1 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "1.6903418264342966",
    distance_string: null,
    bearing: "east",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$48 - $128",
    hotel_class: "4.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e2c40d2d-764d-4216-b2ee-c33df1396e80",
  },
  {
    location_id: "304704",
    name: "The Ummed Ahmedabad",
    latitude: "23.081804",
    longitude: "72.61629",
    num_reviews: "1194",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1b/b7/b9/d2/other.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1b/b7/b9/d2/other.jpg",
          height: "50",
        },
        original: {
          width: "4102",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1b/b7/b9/d2/other.jpg",
          height: "2148",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1b/b7/b9/d2/other.jpg",
          height: "288",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1b/b7/b9/d2/other.jpg",
          height: "131",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-08-07T23:39:13-0400",
      caption: "Other",
      id: "465025490",
      helpful_votes: "0",
      published_date: "2020-08-07T23:39:13-0400",
      user: null,
    },
    awards: [
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2021",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2021_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2021",
      },
    ],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "4.713027000427246",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "2",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#2 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.8320410616284275",
    distance_string: null,
    bearing: "southeast",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$51 - $272",
    hotel_class: "4.5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "2c8907da-f4ca-4816-84b2-b8dd519321bc",
  },
  {
    location_id: "14006373",
    name: "Tribecca Select",
    latitude: "23.118578",
    longitude: "72.62454",
    num_reviews: "42",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1c/2e/0c/69/suite-room.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1c/2e/0c/69/suite-room.jpg",
          height: "50",
        },
        original: {
          width: "4000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1c/2e/0c/69/suite-room.jpg",
          height: "2666",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1c/2e/0c/69/suite-room.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1c/2e/0c/69/suite-room.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-10-15T07:25:28-0400",
      caption: "Suite Room",
      id: "472779881",
      helpful_votes: "0",
      published_date: "2020-10-15T07:25:28-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.4310543537139893",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "3",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#3 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.6089195340686726",
    distance_string: null,
    bearing: "northeast",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$37 - $78",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "3f476e28-6e56-4832-b67e-6ec5bf2ef256",
  },
  {
    location_id: "3801139",
    name: "Hotel Kanan",
    latitude: "23.1165",
    longitude: "72.63125",
    num_reviews: "1",
    timezone: "Asia/Kolkata",
    location_string: "Gandhinagar, Gandhinagar District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/10/47/fa/a4/hotel-kanan.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/10/47/fa/a4/hotel-kanan.jpg",
          height: "50",
        },
        original: {
          width: "1024",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/10/47/fa/a4/hotel-kanan.jpg",
          height: "681",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/10/47/fa/a4/hotel-kanan.jpg",
          height: "365",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/10/47/fa/a4/hotel-kanan.jpg",
          height: "166",
        },
      },
      is_blessed: true,
      uploaded_date: "2017-08-15T04:32:53-0400",
      caption: "",
      id: "273152676",
      helpful_votes: "0",
      published_date: "2017-08-15T04:32:53-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.0149171352386475",
    ranking_geo: "Gandhinagar",
    ranking_geo_id: "297609",
    ranking_position: "4",
    ranking_denominator: "1268",
    ranking_category: "bb",
    ranking: "#4 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "1.9159585592163668",
    distance_string: null,
    bearing: "northeast",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$30 - $42",
    hotel_class: "2.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "8bd3c127-492e-4b03-9a28-5c9a2f5e06ba",
  },
  {
    location_id: "4166805",
    name: "YMCA International Centre",
    latitude: "23.11331",
    longitude: "72.60742",
    num_reviews: "86",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/0a/9b/bc/a1/ymca-international-centre.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/0a/9b/bc/a1/ymca-international-centre.jpg",
          height: "50",
        },
        original: {
          width: "1496",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/0a/9b/bc/a1/ymca-international-centre.jpg",
          height: "2000",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-p/0a/9b/bc/a1/ymca-international-centre.jpg",
          height: "735",
        },
        medium: {
          width: "337",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/0a/9b/bc/a1/ymca-international-centre.jpg",
          height: "450",
        },
      },
      is_blessed: true,
      uploaded_date: "2016-03-16T14:19:06-0400",
      caption: "",
      id: "177978529",
      helpful_votes: "3",
      published_date: "2016-03-16T14:19:06-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2018",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2018_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2018",
      },
    ],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.3474655151367188",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "5",
    ranking_denominator: "1268",
    ranking_category: "bb",
    ranking: "#5 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "0.5886223997215654",
    distance_string: null,
    bearing: "northeast",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$49 - $66",
    hotel_class: "4.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "90dc0c1d-a430-4d2e-a3d2-2502c5aa0289",
  },
  {
    location_id: "1892719",
    name: "Pristine Residency Hotel",
    latitude: "23.079973",
    longitude: "72.617676",
    num_reviews: "149",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/02/25/c5/03/pristine-residency-hotel.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/02/25/c5/03/pristine-residency-hotel.jpg",
          height: "50",
        },
        original: {
          width: "945",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/02/25/c5/03/pristine-residency-hotel.jpg",
          height: "386",
        },
        large: {
          width: "945",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/02/25/c5/03/pristine-residency-hotel.jpg",
          height: "386",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/02/25/c5/03/pristine-residency-hotel.jpg",
          height: "224",
        },
      },
      is_blessed: false,
      uploaded_date: "2011-10-05T17:25:07-0400",
      caption: "Pristine Residency Hotel",
      id: "36029699",
      helpful_votes: "2",
      published_date: "2011-10-05T17:25:05-0400",
      user: null,
    },
    awards: [
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2019",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2019_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2019",
      },
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2018",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2018_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2018",
      },
      {
        award_type: "CERTIFICATE_OF_EXCELLENCE",
        year: "2017",
        images: {
          small:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_small-0-5.jpg",
          large:
            "https://www.tripadvisor.com/img/cdsi/img2/awards/CERTIFICATE_OF_EXCELLENCE_2017_en_US_large-0-5.jpg",
        },
        categories: [],
        display_name: "Certificate of Excellence 2017",
      },
    ],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.5198562145233154",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "6",
    ranking_denominator: "1268",
    ranking_category: "bb",
    ranking: "#6 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "1.9848285496631188",
    distance_string: null,
    bearing: "southeast",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$37 - $47",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "de5f1c47-52e8-4635-9989-59966165616a",
  },
  {
    location_id: "297608",
    ad_position: "inline1",
    ad_size: "8X8",
    doubleclick_zone: "as.india.gujarat.ahmedabad",
    ancestors: [
      {
        subcategory: [
          {
            key: "district",
            name: "District",
          },
        ],
        name: "Ahmedabad District",
        abbrv: null,
        location_id: "12385355",
      },
      {
        subcategory: [
          {
            key: "state",
            name: "State",
          },
        ],
        name: "Gujarat",
        abbrv: null,
        location_id: "297607",
      },
      {
        subcategory: [
          {
            key: "country",
            name: "Country",
          },
        ],
        name: "India",
        abbrv: null,
        location_id: "293860",
      },
    ],
    detail: "0",
    page_type: "hotels",
    mob_ptype: "app_hotels",
  },
  {
    location_id: "299355",
    name: "Comfort Inn Sunset",
    latitude: "23.080935",
    longitude: "72.61702",
    num_reviews: "145",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1e/9a/58/54/hotel-exterior.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1e/9a/58/54/hotel-exterior.jpg",
          height: "50",
        },
        original: {
          width: "1023",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1e/9a/58/54/hotel-exterior.jpg",
          height: "682",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1e/9a/58/54/hotel-exterior.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1e/9a/58/54/hotel-exterior.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-09-29T01:41:42-0400",
      caption: "Hotel exterior",
      id: "513431636",
      helpful_votes: "0",
      published_date: "2021-09-29T01:41:42-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.295642614364624",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "7",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#7 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.9066572714264725",
    distance_string: null,
    bearing: "southeast",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$52 - $71",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "8b454f24-acb2-4284-8f27-2b23031d4d41",
  },
  {
    location_id: "14059919",
    name: "Hotel Sunstar Inn",
    latitude: "23.111395",
    longitude: "72.58451",
    num_reviews: "1",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1a/93/c8/7d/hotel-sunstar-inn.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1a/93/c8/7d/hotel-sunstar-inn.jpg",
          height: "50",
        },
        original: {
          width: "6240",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1a/93/c8/7d/hotel-sunstar-inn.jpg",
          height: "4160",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1a/93/c8/7d/hotel-sunstar-inn.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1a/93/c8/7d/hotel-sunstar-inn.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-01-12T01:42:39-0500",
      caption: "",
      id: "445892733",
      helpful_votes: "0",
      published_date: "2020-01-12T01:42:39-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.033780336380005",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "8",
    ranking_denominator: "1268",
    ranking_category: "other",
    ranking: "#8 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "specialty_hotel",
    subcategory_type_label: "Specialty Hotel",
    distance: "1.2781454294659231",
    distance_string: null,
    bearing: "west",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$19 - $31",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "67055f9f-a879-4b41-8600-9193e5cadaed",
  },
  {
    location_id: "23470277",
    name: "Hotel Sun Square",
    latitude: "23.11541",
    longitude: "72.58246",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-l/21/47/c4/1d/caption.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/21/47/c4/1d/caption.jpg",
          height: "50",
        },
        original: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/47/c4/1d/caption.jpg",
          height: "413",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/47/c4/1d/caption.jpg",
          height: "413",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/21/47/c4/1d/caption.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-10-30T05:10:07-0400",
      caption: "",
      id: "558351389",
      helpful_votes: "0",
      published_date: "2021-10-30T05:10:07-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "9",
    ranking_denominator: "1268",
    ranking: "#9 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "1.5060958146947265",
    distance_string: null,
    bearing: "northwest",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "fbe4945a-05ee-499f-b541-5a873b6331d7",
  },
  {
    location_id: "14067209",
    name: "OYO 3056 Hotel Sigma Inn",
    latitude: "23.101135",
    longitude: "72.58771",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1a/7d/b8/d3/oyo-3056-hotel-sigma.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1a/7d/b8/d3/oyo-3056-hotel-sigma.jpg",
          height: "50",
        },
        original: {
          width: "960",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1a/7d/b8/d3/oyo-3056-hotel-sigma.jpg",
          height: "640",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1a/7d/b8/d3/oyo-3056-hotel-sigma.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1a/7d/b8/d3/oyo-3056-hotel-sigma.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-01-04T01:00:20-0500",
      caption: "",
      id: "444446931",
      helpful_votes: "0",
      published_date: "2020-01-04T01:00:20-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "10",
    ranking_denominator: "1268",
    ranking: "#10 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "1.055206390194661",
    distance_string: null,
    bearing: "west",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$20 - $28",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "84fcd933-4ea4-4104-a13e-e8700aad1b68",
  },
  {
    location_id: "9977692",
    name: "Hotel German Palace, Airport",
    latitude: "23.111252",
    longitude: "72.6313",
    num_reviews: "89",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/0a/53/bd/c6/getlstd-property-photo.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/0a/53/bd/c6/getlstd-property-photo.jpg",
          height: "50",
        },
        original: {
          width: "1024",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/0a/53/bd/c6/getlstd-property-photo.jpg",
          height: "768",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/0a/53/bd/c6/getlstd-property-photo.jpg",
          height: "412",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/0a/53/bd/c6/getlstd-property-photo.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2016-02-15T02:26:34-0500",
      caption: "getlstd_property_photo",
      id: "173260230",
      helpful_votes: "1",
      published_date: "2016-02-15T02:26:34-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.7060084342956543",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "11",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#11 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.8071446910510571",
    distance_string: null,
    bearing: "east",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$50 - $73",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "43627ee0-11b8-490d-a55e-b4bab10722bf",
  },
  {
    location_id: "17847997",
    name: "Hotel Royal Square by Sky Stays",
    latitude: "23.12909",
    longitude: "72.58431",
    num_reviews: "1",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1c/88/1c/fd/hotel-royal-square-by.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1c/88/1c/fd/hotel-royal-square-by.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1c/88/1c/fd/hotel-royal-square-by.jpg",
          height: "1334",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1c/88/1c/fd/hotel-royal-square-by.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1c/88/1c/fd/hotel-royal-square-by.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-01-16T04:10:54-0500",
      caption: "",
      id: "478682365",
      helpful_votes: "0",
      published_date: "2021-01-16T04:10:54-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.041985511779785",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "12",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#12 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.036795796861507",
    distance_string: null,
    bearing: "northwest",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$17 - $33",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "27e476d4-935f-4844-be8d-ec5598a407c2",
  },
  {
    location_id: "21128899",
    name: "OYO 64029 Hotel Phoenix",
    latitude: "23.119022",
    longitude: "72.6137",
    num_reviews: "1",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/21/1e/50/1f/caption.jpg",
          height: "137",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/21/1e/50/1f/caption.jpg",
          height: "50",
        },
        original: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/1e/50/1f/caption.jpg",
          height: "460",
        },
        large: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/1e/50/1f/caption.jpg",
          height: "460",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/1e/50/1f/caption.jpg",
          height: "301",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-10-27T11:49:04-0400",
      caption: "",
      id: "555634719",
      helpful_votes: "0",
      published_date: "2021-10-27T11:49:04-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.0412542819976807",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "13",
    ranking_denominator: "1268",
    ranking_category: "other",
    ranking: "#13 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "specialty_hotel",
    subcategory_type_label: "Specialty Hotel",
    distance: "1.1316836600525",
    distance_string: null,
    bearing: "northeast",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e1fa9495-3f5f-4fc6-a136-ce8aa69d7a21",
  },
  {
    location_id: "21507935",
    name: "Hotel Runway Inn",
    latitude: "23.081192",
    longitude: "72.63316",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/1c/78/58/a7/6839307.jpg",
          height: "137",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1c/78/58/a7/6839307.jpg",
          height: "50",
        },
        original: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1c/78/58/a7/6839307.jpg",
          height: "460",
        },
        large: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1c/78/58/a7/6839307.jpg",
          height: "460",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1c/78/58/a7/6839307.jpg",
          height: "301",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-12-29T00:12:13-0500",
      caption: "Hotel Runway Inn",
      id: "477649063",
      helpful_votes: "0",
      published_date: "2020-12-29T00:12:13-0500",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "14",
    ranking_denominator: "1268",
    ranking: "#14 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "2.5273059672412046",
    distance_string: null,
    bearing: "southeast",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "f1d8a3ec-fad6-4d6c-9ed4-e311be69210b",
  },
  {
    location_id: "297608",
    ad_position: "inline2",
    ad_size: "8X8",
    doubleclick_zone: "as.india.gujarat.ahmedabad",
    ancestors: [
      {
        subcategory: [
          {
            key: "district",
            name: "District",
          },
        ],
        name: "Ahmedabad District",
        abbrv: null,
        location_id: "12385355",
      },
      {
        subcategory: [
          {
            key: "state",
            name: "State",
          },
        ],
        name: "Gujarat",
        abbrv: null,
        location_id: "297607",
      },
      {
        subcategory: [
          {
            key: "country",
            name: "Country",
          },
        ],
        name: "India",
        abbrv: null,
        location_id: "293860",
      },
    ],
    detail: "0",
    page_type: "hotels",
    mob_ptype: "app_hotels",
  },
  {
    location_id: "21222016",
    name: "Hotel Sparsh Inn",
    latitude: "23.123808",
    longitude: "72.58116",
    num_reviews: "10",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/16/f4/c0/29/oyo-16604-hotel-sparsh.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/16/f4/c0/29/oyo-16604-hotel-sparsh.jpg",
          height: "50",
        },
        original: {
          width: "960",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/16/f4/c0/29/oyo-16604-hotel-sparsh.jpg",
          height: "640",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/16/f4/c0/29/oyo-16604-hotel-sparsh.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/16/f4/c0/29/oyo-16604-hotel-sparsh.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2019-03-27T09:37:13-0400",
      caption: "",
      id: "385138729",
      helpful_votes: "0",
      published_date: "2019-03-27T09:37:13-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.2109010219573975",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "15",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#15 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.9039234991142284",
    distance_string: null,
    bearing: "northwest",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "2.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "dba40c81-e008-42d6-8250-78b7a79ae8fd",
  },
  {
    location_id: "19763283",
    name: "OYO 36139 Hotel Sunway",
    latitude: "23.081163",
    longitude: "72.62289",
    num_reviews: "2",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1a/ba/2c/e7/oyo-36139-hotel-sunway.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1a/ba/2c/e7/oyo-36139-hotel-sunway.jpg",
          height: "50",
        },
        original: {
          width: "960",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1a/ba/2c/e7/oyo-36139-hotel-sunway.jpg",
          height: "640",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1a/ba/2c/e7/oyo-36139-hotel-sunway.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1a/ba/2c/e7/oyo-36139-hotel-sunway.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-01-28T00:32:32-0500",
      caption: "",
      id: "448408807",
      helpful_votes: "0",
      published_date: "2020-01-28T00:32:32-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "2.4993181228637695",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "16",
    ranking_denominator: "1268",
    ranking_category: "other",
    ranking: "#16 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "specialty_hotel",
    subcategory_type_label: "Specialty Hotel",
    distance: "2.0879643029708173",
    distance_string: null,
    bearing: "southeast",
    rating: "1.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "804cf1ec-35ad-4680-bcea-fbc73428120a",
  },
  {
    location_id: "7297366",
    name: "Hotel Hillton Inn",
    latitude: "23.116783",
    longitude: "72.60216",
    num_reviews: "3",
    timezone: "Asia/Kolkata",
    location_string: "Gandhinagar, Gandhinagar District, Gujarat",
    photo: {
      images: {
        small: {
          width: "550",
          url: null,
          height: "550",
        },
        thumbnail: {
          width: "550",
          url: null,
          height: "550",
        },
        original: {
          width: "550",
          url: null,
          height: "550",
        },
        large: {
          width: "550",
          url: null,
          height: "550",
        },
        medium: {
          width: "550",
          url: null,
          height: "550",
        },
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "2.652616024017334",
    ranking_geo: "Gandhinagar",
    ranking_geo_id: "297609",
    ranking_position: "17",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#17 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "0.7808641778546075",
    distance_string: null,
    bearing: "north",
    rating: "1.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$25 - $40",
    hotel_class: "2.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e45183ce-3d15-495d-93dd-c26c478dd3dc",
  },
  {
    location_id: "19987307",
    name: "OYO 49537 Hotel Airport Annex",
    latitude: "23.081371",
    longitude: "72.62423",
    num_reviews: "1",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.041843891143799",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "18",
    ranking_denominator: "1268",
    ranking_category: "hotel",
    ranking: "#18 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.1280245500430306",
    distance_string: null,
    bearing: "southeast",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "dd764a77-ce57-4d00-a6c4-b85c20653311",
  },
  {
    location_id: "9558796",
    name: "Homestay Inn",
    latitude: "23.079794",
    longitude: "72.62047",
    num_reviews: "3",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/0a/c2/0d/1d/homestay-inn.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/0a/c2/0d/1d/homestay-inn.jpg",
          height: "50",
        },
        original: {
          width: "1600",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/0a/c2/0d/1d/homestay-inn.jpg",
          height: "1200",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/0a/c2/0d/1d/homestay-inn.jpg",
          height: "412",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/0a/c2/0d/1d/homestay-inn.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2016-03-31T05:32:07-0400",
      caption: "Homestay Inn",
      id: "180489501",
      helpful_votes: "0",
      published_date: "2016-03-31T05:32:07-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "2.9905033111572266",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "19",
    ranking_denominator: "1268",
    ranking_category: "bb",
    ranking: "#19 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "2.081816123792017",
    distance_string: null,
    bearing: "southeast",
    rating: "3.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$17 - $25",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "681fb171-1311-4a57-9008-ed648675fffa",
  },
  {
    location_id: "12400183",
    name: "Hotel Ashray Inn Express",
    latitude: "23.08576",
    longitude: "72.63047",
    num_reviews: "3",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/0f/ac/dd/63/hotel-ashray-inn-express.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/0f/ac/dd/63/hotel-ashray-inn-express.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/0f/ac/dd/63/hotel-ashray-inn-express.jpg",
          height: "1500",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/0f/ac/dd/63/hotel-ashray-inn-express.jpg",
          height: "413",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/0f/ac/dd/63/hotel-ashray-inn-express.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2017-06-25T07:16:07-0400",
      caption: "",
      id: "262987107",
      helpful_votes: "0",
      published_date: "2017-06-25T07:16:07-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.0324645042419434",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "20",
    ranking_denominator: "1268",
    ranking_category: "other",
    ranking: "#20 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "condo",
    subcategory_type_label: "Condominium",
    distance: "2.192164488828224",
    distance_string: null,
    bearing: "southeast",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$30 - $45",
    hotel_class: "3.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "9be0590c-2791-47f6-b657-ee3f15222968",
  },
  {
    location_id: "23479310",
    name: "Hotel Asiana",
    latitude: "23.106752",
    longitude: "72.59796",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1e/40/0b/79/hotel-asiana.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1e/40/0b/79/hotel-asiana.jpg",
          height: "50",
        },
        original: {
          width: "1280",
          url: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1e/40/0b/79/hotel-asiana.jpg",
          height: "960",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1e/40/0b/79/hotel-asiana.jpg",
          height: "413",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1e/40/0b/79/hotel-asiana.jpg",
          height: "188",
        },
      },
      is_blessed: false,
      uploaded_date: "2021-09-25T04:36:20-0400",
      caption: "",
      id: "507513721",
      helpful_votes: "0",
      published_date: "2021-09-25T04:36:20-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "21",
    ranking_denominator: "1268",
    ranking: "#21 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "0.36649407401043177",
    distance_string: null,
    bearing: "west",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "ba6747ab-731a-4b25-82b9-30eca399fe10",
  },
  {
    location_id: "3974633",
    name: "OYO 60599 Kabir Residency",
    latitude: "23.0856",
    longitude: "72.62165",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/21/54/e3/4c/caption.jpg",
          height: "137",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/21/54/e3/4c/caption.jpg",
          height: "50",
        },
        original: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/54/e3/4c/caption.jpg",
          height: "460",
        },
        large: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/54/e3/4c/caption.jpg",
          height: "460",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/54/e3/4c/caption.jpg",
          height: "301",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-11-03T23:53:08-0400",
      caption: "",
      id: "559211340",
      helpful_votes: "0",
      published_date: "2021-11-03T23:53:08-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "22",
    ranking_denominator: "1268",
    ranking: "#22 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "1.797368634319994",
    distance_string: null,
    bearing: "southeast",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$14 - $37",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "8fa74f7f-b5ee-4c0a-b199-0ee699ab2554",
  },
  {
    location_id: "297608",
    ad_position: "inline3",
    ad_size: "8X8",
    doubleclick_zone: "as.india.gujarat.ahmedabad",
    ancestors: [
      {
        subcategory: [
          {
            key: "district",
            name: "District",
          },
        ],
        name: "Ahmedabad District",
        abbrv: null,
        location_id: "12385355",
      },
      {
        subcategory: [
          {
            key: "state",
            name: "State",
          },
        ],
        name: "Gujarat",
        abbrv: null,
        location_id: "297607",
      },
      {
        subcategory: [
          {
            key: "country",
            name: "Country",
          },
        ],
        name: "India",
        abbrv: null,
        location_id: "293860",
      },
    ],
    detail: "0",
    page_type: "hotels",
    mob_ptype: "app_hotels",
  },
  {
    location_id: "16864638",
    name: "OYO 16826 Hotel Marvel Inn",
    latitude: "23.081758",
    longitude: "72.61794",
    num_reviews: "2",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1a/46/47/fc/oyo-16826-hotel-marvel.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1a/46/47/fc/oyo-16826-hotel-marvel.jpg",
          height: "50",
        },
        original: {
          width: "960",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1a/46/47/fc/oyo-16826-hotel-marvel.jpg",
          height: "640",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1a/46/47/fc/oyo-16826-hotel-marvel.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1a/46/47/fc/oyo-16826-hotel-marvel.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2019-12-12T05:37:26-0500",
      caption: "",
      id: "440813564",
      helpful_votes: "0",
      published_date: "2019-12-12T05:37:26-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "2.664400339126587",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "23",
    ranking_denominator: "1268",
    ranking_category: "bb",
    ranking: "#23 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "1.8836870503969574",
    distance_string: null,
    bearing: "southeast",
    rating: "1.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$15 - $25",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "ae3c3d84-3d2c-4d9b-910c-fd73caa36642",
  },
  {
    location_id: "21160809",
    name: "OYO 41587 Hotel Airport Inn One",
    latitude: "23.081486",
    longitude: "72.61686",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-l/20/7e/4f/f9/caption.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/20/7e/4f/f9/caption.jpg",
          height: "50",
        },
        original: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/20/7e/4f/f9/caption.jpg",
          height: "366",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/20/7e/4f/f9/caption.jpg",
          height: "366",
        },
        medium: {
          width: "500",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/20/7e/4f/f9/caption.jpg",
          height: "333",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-10-19T09:38:15-0400",
      caption: "",
      id: "545148921",
      helpful_votes: "0",
      published_date: "2021-10-19T09:38:15-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "24",
    ranking_denominator: "1268",
    ranking: "#24 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "1.8680240121756106",
    distance_string: null,
    bearing: "southeast",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "bdbf0529-faaa-4bd2-b086-b776873ed7a0",
  },
  {
    location_id: "21505505",
    name: "Hotel Runway Inn",
    latitude: "23.080948",
    longitude: "72.632484",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "25",
    ranking_denominator: "1268",
    ranking: "#25 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "2.5067346363036185",
    distance_string: null,
    bearing: "southeast",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "524e741d-ebd0-4949-87cc-8c8239ad8ecb",
  },
  {
    location_id: "10783142",
    name: "Hotel Jaunt Safari Residency",
    latitude: "23.11604",
    longitude: "72.6142",
    num_reviews: "3",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.036128044128418",
    ranking_geo: "Ahmedabad",
    ranking_geo_id: "297608",
    ranking_position: "26",
    ranking_denominator: "1268",
    ranking_category: "bb",
    ranking: "#26 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "0.9904154898836589",
    distance_string: null,
    bearing: "northeast",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$17 - $30",
    hotel_class: "2.0",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "f92c015d-3831-492d-8cc3-5372b0452303",
  },
  {
    location_id: "21509608",
    name: "OYO 49537 Hotel Airport Annex",
    latitude: "23.080244",
    longitude: "72.62491",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/1c/f6/16/f8/bedroom.jpg",
          height: "137",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1c/f6/16/f8/bedroom.jpg",
          height: "50",
        },
        original: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1c/f6/16/f8/bedroom.jpg",
          height: "460",
        },
        large: {
          width: "840",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1c/f6/16/f8/bedroom.jpg",
          height: "460",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1c/f6/16/f8/bedroom.jpg",
          height: "301",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-05-10T23:45:10-0400",
      caption: "Bedroom",
      id: "485889784",
      helpful_votes: "0",
      published_date: "2021-05-10T23:45:10-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "27",
    ranking_denominator: "1268",
    ranking: "#27 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "2.2160819113720573",
    distance_string: null,
    bearing: "southeast",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "4b3056f8-f22e-4f44-afd4-a8ec5a95299b",
  },
  {
    location_id: "4274637",
    name: "Aalloa Hills Resort",
    latitude: "23.11126",
    longitude: "72.62886",
    num_reviews: "11",
    timezone: "Asia/Kolkata",
    location_string: "Gandhinagar, Gandhinagar District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/08/18/9a/13/moments-with-nature.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/08/18/9a/13/moments-with-nature.jpg",
          height: "50",
        },
        original: {
          width: "1936",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/08/18/9a/13/moments-with-nature.jpg",
          height: "2592",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-p/08/18/9a/13/moments-with-nature.jpg",
          height: "736",
        },
        medium: {
          width: "336",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/08/18/9a/13/moments-with-nature.jpg",
          height: "450",
        },
      },
      is_blessed: true,
      uploaded_date: "2015-06-14T05:57:28-0400",
      caption: "Moments with nature",
      id: "135830035",
      helpful_votes: "0",
      published_date: "2015-06-16T02:41:20-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    raw_ranking: "3.0746660232543945",
    ranking_geo: "Gandhinagar",
    ranking_geo_id: "297609",
    ranking_position: "28",
    ranking_denominator: "1268",
    ranking_category: "other",
    ranking: "#28 Best Value of 1,268 places to stay in Ahmedabad",
    subcategory_type: "lodge",
    subcategory_type_label: "Lodge",
    distance: "1.6560092557129036",
    distance_string: null,
    bearing: "east",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$44 - $62",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "dcd963e1-7866-4793-8d29-6df9570c90e3",
  },
  {
    location_id: "21139068",
    name: "Hotel New Empire",
    latitude: "23.100586",
    longitude: "72.60103",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-l/21/38/e4/7d/caption.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/21/38/e4/7d/caption.jpg",
          height: "50",
        },
        original: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/38/e4/7d/caption.jpg",
          height: "367",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/21/38/e4/7d/caption.jpg",
          height: "367",
        },
        medium: {
          width: "500",
          url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/21/38/e4/7d/caption.jpg",
          height: "334",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-10-29T05:48:00-0400",
      caption: "",
      id: "557376637",
      helpful_votes: "0",
      published_date: "2021-10-29T05:48:00-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "29",
    ranking_denominator: "1268",
    ranking: "#29 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "0.38095784148446404",
    distance_string: null,
    bearing: "southwest",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "998fb891-ce39-4919-99e2-4f9faf6bc52f",
  },
  {
    location_id: "21507737",
    name: "Hotel Season",
    latitude: "23.08276",
    longitude: "72.620926",
    num_reviews: "0",
    timezone: "Asia/Kolkata",
    location_string: "Ahmedabad, Ahmedabad District, Gujarat",
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Ahmedabad Places to Stay",
    ranking_position: "30",
    ranking_denominator: "1268",
    ranking: "#30 Best Value of 1,268 places to stay in Ahmedabad",
    distance: "1.92559766929656",
    distance_string: null,
    bearing: "southeast",
    is_closed: false,
    is_long_closed: false,
    price_level: "",
    hotel_class: "0.0",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "cbf074a0-1ace-44cb-97e2-238c9c47d079",
  },
];

export default data;